---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hetzner-csi-driver
  namespace: argocd
spec:
  project: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  sources:
    - repoURL: git@github.com:flynnt-io/flynnt-kafka-strimzi-sample.git
      path: applications/hetzner-csi-driver
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
spec:
  project: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: strimzi-operator
  sources:
    - repoURL: quay.io/strimzi-helm
      chart: strimzi-kafka-operator
      targetRevision: 0.38.0
      helm:
        values: |
          watchAnyNamespace: true
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true